name: kitchen
channels:
  - pytorch      # Specific channel for PyTorch packages
  - conda-forge  # Prefer community-maintained packages first
  - fastai       # Added for opencv-python-headless (if necessary)
  - defaults     # Default channel as fallback
dependencies:
  - python=3.10
  - numpy=1.26.4
  - scipy
  - qpsolvers
  - albumentations
  - imageio[ffmpeg]
  - ninja
  - gdown
  - ipykernel
  - ipympl
  - matplotlib
  - tqdm
  - tabulate
  - cython
  - conda-forge::colmap
  - conda-forge::captum
  - fastai::opencv-python-headless=4.10.0.84
  - pip
  - pip:
    - https://download.pytorch.org/whl/cu130/torch-2.10.0%2Bcu130-cp310-cp310-manylinux_2_28_x86_64.whl#sha256=0f8566d1b3d8353b7f18d5a15375a00dae89d886bb7d01143bb394f475832286
    - https://download.pytorch.org/whl/cu130/torchvision-0.25.0%2Bcu130-cp310-cp310-manylinux_2_28_x86_64.whl#sha256=9391dc5b2e038a5e365d07b425e4046fb8f605eeb6095fcb90f38a7b6c0aba7c
    - git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch
    #- nerfstudio==1.1.4
    #- pyrealsense2
    #- -e ./FiGS/
    #- -e ./FiGS/acados/interfaces/acados_template/
    #- -e ./FiGS/Hierarchical-Localization/
    #- -e .
