
[project]
name = "sousvide"
version = "0.1.0"
description = "Scene Understanding via Synthesized Visual Inertial Data from Experts"
authors = [{ name = "JunEn Low", email = "lowjunen@gmail.com.com" }]
license = { file = "LICENSE" }
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
]

[tool.setuptools.packages.find]
where = ["src"]

#colmap installed with CMAKE_ARGS="-DCOLMAP_DIR=/home/airlab/colmap/build -DCMAKE_CUDA_ARCHITECTURES=120"  LDFLAGS="-Wl,-rpath,${CONDA_PREFIX}/lib -L${CONDA_PREFIX}/lib" pixi run pip install ~/colmap/