import numpy as np
import os
import torch

import sousvide.synthesize.data_compress_helper as dch
from sousvide.synthesize.image_modality import (
    ImageModality,get_aligned_stack_files,prepare_rollout_images,
    validate_image_modality,
)
import sousvide.control.network_helper as nh
import sousvide.visualize.rich_utilities as ru
from sousvide.instruct.synthesized_data import (
    OBSERVATION_FORMAT_VERSION,stack_samples)

from rich.progress import Progress
from sousvide.control.pilot import Pilot

def generate_observation_data(cohort:str,roster:list[str],
                              networks:list[str]|None=None,
                              subsample:float=1.0,
                              image_modality:ImageModality="rgb") -> None:
    """
    Takes rollout data and generates observations for each pilot in the cohort. The observations are
    generated by running the rollout data through the pilot's OODA function. The observations are saved
    to a .pt file in the pilot's directory.

    Args:
        cohort:             Cohort name.
        roster:             List of student names.
        subsample:          Subsample ratio for the observations.
        image_modality:     Visual input to generate observations from.

    """

    # Initialize the progress variables
    image_modality = validate_image_modality(image_modality)
    console = ru.get_console()
    progress = ru.get_generation_progress()
    subunits = "dpts"
    obsv_desc1 = "[bold dark_green]Generating observations...[/]"
    obsv_desc2 = "[bold dark_green]Saving dataset...[/]"
    
    # Generate some useful intermediate variables
    workspace_path = os.path.dirname(
        os.path.dirname(os.path.dirname(os.path.dirname(__file__))))
    cohort_path = os.path.join(workspace_path,"cohorts",cohort)
    rollout_folder_path = os.path.join(cohort_path,"rollout_data")

    # Extract some useful diagnostics info
    courses = [folder for folder in os.listdir(rollout_folder_path)]

    Nds = 0
    for course in courses:
        dset_files = os.listdir(os.path.join(rollout_folder_path, course, "trajectories"))
        Nds += len(dset_files)

    # Preface Message
    console.print(f"Generating observation data with subsample ratio {subsample} for...\n",
                  f"Cohort : [green4]{cohort}[/]\n",
                  f"Roster : {roster}\n",
                  f"Courses: {courses}")

    with progress:
        # Initialize observations progress bar
        obsv_task = progress.add_task(obsv_desc1,total=None,units='samples')

        # Extract observations for each student
        for student in roster:
            # Load the Pilot
            pilot = Pilot(
                cohort,student,image_modality=image_modality)

            # Check if the student has desired networks
            if networks is not None:
                if set(networks).isdisjoint(pilot.policy.networks):
                    console.print(f"Pilot [bold cyan]{student}[/] does not have network [bold cyan]{networks}[/].")
                    continue

            # Initialize student progress bar
            Ndata = 0
            network_names = "\["+",".join(list(pilot.policy.networks.keys()))+"]"
            student_tname = f"[bold green3]{student:>8} > {network_names}[/]\n     [dark_green]Data Count:[/]"
            student_desc = ru.get_data_description(student_tname,Ndata,subunits=subunits,Nmn=20)
            student_task = progress.add_task(student_desc,total=Nds, units='datasets')
            
            for course in courses:
                ro_data_path = os.path.join(rollout_folder_path,course)
                stack_paths = get_aligned_stack_files(ro_data_path,image_modality)
                
                # Generate Observation Data
                for idx_ds,(traj_data_path,imgs_data_path) in enumerate(stack_paths):
                    # Load the Data
                    traj_ds = torch.load(traj_data_path,weights_only=False,encoding='bytes')
                    imgs_ds = torch.load(imgs_data_path,weights_only=False,encoding='bytes')

                    # Reset the observations progress bar
                    progress.reset(obsv_task,description=obsv_desc1,total=len(traj_ds))
                    obsv_bar = (progress,obsv_task)
    
                    # Extract the Observations
                    observations,Nobs = generate_observations(
                        pilot,traj_ds,imgs_ds,subsample,obsv_bar,image_modality,
                        networks=networks)
                    
                    # Update the observations progress bar
                    progress.update(obsv_task,description=obsv_desc2)
                    progress.refresh()

                    # Save the observations
                    save_observations(
                        cohort_path,course,pilot.name,observations,idx_ds,networks,image_modality)

                    # Update the number of data points
                    Ndata += Nobs

                    # Update the progress bar
                    student_desc = ru.get_data_description(student_tname,Ndata,subunits=subunits)
                    progress.update(student_task,description=student_desc,advance=1)

                # Cap off progress update
                progress.refresh()

def generate_observations(pilot:Pilot,
                          traj_set:dict[str,str|int|dict[str,np.ndarray|float,str]],
                          imgs_set:dict[str,str|int|dict[str,np.ndarray|float,str]],
                          subsample:float=1,
                          progress_bar:tuple[Progress,int]=None,
                          image_modality:ImageModality="rgb",
                          networks:list[str]|None=None
                          ) -> tuple[dict[str,str|int|dict[str,np.ndarray|float,str]],int]:
    
    # Initialize the observation data dictionary
    Observations = []
    image_modality = validate_image_modality(image_modality)
    if len(traj_set) != len(imgs_set):
        raise ValueError("Trajectory and image rollout counts do not match.")
    expected_dimensions = None

    # Unpack augmenteation variables
    aug_type = np.array(pilot.da_cfg["type"])
    aug_mean = np.array(pilot.da_cfg["mean"])
    aug_std = np.array(pilot.da_cfg["std"])

    # Set subsample step
    nss = int(1/subsample)

    Nobs = 0
    for traj_data,imgs_data in zip(traj_set,imgs_set):
        # Unpack data
        Tro,Xro = traj_data["Tro"],traj_data["Xro"]
        Uro,Wro = traj_data["Uro"],traj_data["Wro"]
        Wrs = traj_data["Wrs"]
        Ndata = traj_data["Ndata"]
        rollout_id = traj_data["rollout_id"]
        frame,params = traj_data["frame"],traj_data["params"]
        if not (len(Uro) == len(Wro) == len(Wrs) == Ndata):
            raise ValueError(f"Control and trajectory counts do not match for {rollout_id}.")
    
        # Kronecker grayscale frames are repeated only in memory, retaining
        # the current three-channel backbone and rgb_image network input.
        Rgbs = prepare_rollout_images(traj_data,imgs_data,image_modality)

        # Check if images are raw or processed. Raw images are in (B,H,W,C) format while
        # processed images are in (B,C,H,W) format.
        height,width = Rgbs.shape[1],Rgbs.shape[2]
        if expected_dimensions is None:
            expected_dimensions = (height,width)
        elif expected_dimensions != (height,width):
            raise ValueError("Image height and width differ within the rollout stack.")

        if image_modality == "rgb" and height == 224 and width == 224:
            Rgbs = np.transpose(Rgbs, (0, 3, 1, 2))

        # Generate the observation data
        Xnn,Ynn = [],[]
        upr = np.zeros(4)
        for k in range(Ndata):
            # Generate current state (with/without noise augmentation)
            if aug_type == "additive":
                xcr = Xro[k,:] + np.random.normal(aug_mean,aug_std)
            elif aug_type == "multiplicative":
                xcr = Xro[k,:] * (1 + np.random.normal(aug_mean,aug_std))
            else:
                xcr = Xro[k,:]

            # Extract other data
            tcr,ucr = Tro[k],Uro[k,:]            
            txcr = np.hstack((Tro[k],Xro[k,:]))
            wro_cr = Wro[k,:]
            wrs_cr = Wrs[k,:]
            rgb_cr = Rgbs[k,:,:,:]
            
            if networks is None:
                # Preserve the original full-policy behavior for callers that
                # request observation data for every network.
                _,Dnn_cr,_ = pilot.ORCA(
                    tcr,xcr,upr,rgb_cr,None,wro_cr)
            else:
                # Roll out sensor/history state, then collect only the requested
                # prediction inputs. Prerequisite networks execute, but the final
                # target (normally CommNet) does not needlessly run.
                pilot.observe(tcr,xcr,upr,rgb_cr,None,wro_cr)
                pilot.retain()
                Xnn_cr = pilot.collate()
                Dnn_cr = pilot.policy.collect_prediction_inputs(
                    Xnn_cr,networks)

            # Compute the source labels
            ynn_srcs = {
                "current": torch.tensor(txcr,dtype=torch.float32).unsqueeze(0),
                "parameters": torch.tensor(params,dtype=torch.float32).unsqueeze(0),
                "wrench": torch.tensor(wro_cr,dtype=torch.float32).unsqueeze(0),
                "resultant": torch.tensor(wrs_cr,dtype=torch.float32).unsqueeze(0),
                "command": torch.tensor(ucr,dtype=torch.float32).unsqueeze(0),
                "patches": pilot.pch_cr.cpu().clone(),
                "class_token": pilot.cls_cr.cpu().clone()
            }

            # Extract the labels from source and trim inputs if they don't exist
            Ynn_cr = {}
            for dnn_key in Dnn_cr.keys():
                # if dnn_key != "featNet":
                ynn_idxs = pilot.policy.networks[dnn_key].io_idxs["ypd"]
                ynn_cr = nh.extract_io(ynn_srcs,ynn_idxs)
                Ynn_cr[dnn_key] = ynn_cr

            # Collect data conditioned on subsample step and history window
            if k % nss == 0:
                Xnn.append(Dnn_cr)
                Ynn.append(Ynn_cr)

            # Loop updates
            upr = ucr

        # Update the progress bar
        if progress_bar is not None:
            progress,obsv_task = progress_bar
            progress.update(obsv_task,advance=1)
            progress.refresh()

        # Store the observation data
        observations = {
            "Xnn":Xnn,
            "Ynn":Ynn,
            "Ndata":len(Xnn),
            "rollout_id":rollout_id,
            "frame":frame
        }
        Observations.append(observations)

        # Update the counters
        Nobs += len(Xnn)

    return Observations,Nobs

def save_observations(cohort_name:str,course_name:str,
                      pilot_name:str,
                      Observations:list[dict[str,list[dict[str,torch.Tensor]]]],
                      idx_set:int,networks:list[str]|None=None,
                      image_modality:ImageModality="rgb") -> None:
    
    """
    Saves the observation data to a .pt file in folders corresponding to pilot name within the course
    directory within the cohort directory.

    Args:
        cohort_path:    Cohort path.
        course_name:    Name of the course.
        pilot_name:     Name of the pilot.
        Observations:   Observation data.
        idx_set:        Index of the observation data set.
        networks:       List of network names to filter observations (optional).

    Returns:
        None:           (observation data saved to cohort directory)
    """
    
    # Some useful path(s)
    workspace_path = os.path.dirname(
        os.path.dirname(os.path.dirname(os.path.dirname(__file__))))
    cohort_path = os.path.join(workspace_path,"cohorts",cohort_name)
    image_modality = validate_image_modality(image_modality)

    # Use first observation to get relevant keys
    if not Observations or not Observations[0]["Ynn"]:
        return
    syllabus = []
    for key,value in Observations[0]["Ynn"][0].items():
        if value is not None:
            if networks is None or key in networks:
                syllabus.append(key)

    for topic_name in syllabus:
        # Create the topic directory if it doesn't exist
        topic_parts = [cohort_path,"observation_data",pilot_name]
        if image_modality == "kronecker_delta":
            topic_parts.append(image_modality)
        topic_parts.extend([topic_name,course_name])
        topic_path = os.path.join(*topic_parts)
        if not os.path.exists(topic_path):
            os.makedirs(topic_path)

        # Save the observation data
        data_path = os.path.join(topic_path,"observations"+str(idx_set+1).zfill(3)+".pt")

        Xnn,Ynn = [],[]
        for observations in Observations:
            for xnn,ynn in zip(observations["Xnn"],observations["Ynn"]):
                Xnn.append(xnn[topic_name])
                Ynn.append(ynn[topic_name])

        data = {
            "format_version":OBSERVATION_FORMAT_VERSION,
            "Xnn":stack_samples(Xnn),
            "Ynn":stack_samples(Ynn),
            "Ndata":len(Ynn),
        }
        
        torch.save(data,data_path)
